// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Pdoxcl2Sharp")]
[assembly: AssemblyProductAttribute("Pdoxcl2Sharp")]
[assembly: AssemblyDescriptionAttribute("A Paradox Interactive general file parser")]
[assembly: AssemblyVersionAttribute("0.5.2")]
[assembly: AssemblyFileVersionAttribute("0.5.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.5.2";
    }
}
